#!/usr/bin/env python3
import argparse,json
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('--corpus',type=Path,required=True);p.add_argument('--frontend',type=Path,required=True);p.add_argument('--production',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args()
corpus=json.loads(a.corpus.read_text());front={r['id']:r for r in json.loads(a.frontend.read_text())['queries']};production={r['id']:r for r in json.loads(a.production.read_text())['queries']};out=[]
for q in corpus['queries']:
 f=front[q['id']];m=f['metricsql'];pc=production[q['id']];sf=f['clickhouse_sql'];sp=sf.get('status','pass')
 langs={'metricsql':{'parser_canonical':m['parser_canonical'],'planner':m['planner'],'compiler':pc['compile'],'publication':pc.get('publication',{'status':'not_reached'}),'binder':{'status':'not_reached'},'validator':{'status':'not_reached'},'executor':{'status':'not_reached'}},'clickhouse_sql':{'exact_sql_oracle':{'status':q['sql_mapping_status']},'parser_canonical':sf,'planner':{'status':'not_reached' if sp!='pass' else 'pass'},'publication':{'status':'not_reached'},'binder':{'status':'not_reached'},'validator':{'status':'not_reached'},'executor':{'status':'not_reached'}}};out.append({'id':q['id'],'operators':q['operators'],'languages':langs})
report={'schema_version':2,'denominator':27,'evidence':{'metricsql_parser_pass':sum(r['languages']['metricsql']['parser_canonical']['status']=='pass' for r in out),'metricsql_planner_pass':sum(r['languages']['metricsql']['planner']['status']=='pass' for r in out),'metricsql_compiler_pass':sum(r['languages']['metricsql']['compiler']['status']=='pass' for r in out),'metricsql_publication_pass':sum(r['languages']['metricsql']['publication']['status']=='pass' for r in out),'sql_acceleration_frontend_pass':sum(r['languages']['clickhouse_sql']['parser_canonical'].get('status','pass')=='pass' for r in out)},'queries':out};a.output.write_text(json.dumps(report,indent=2)+'\n')
