[package]
name = "asap-physical-operators"
version.workspace = true
edition.workspace = true

[dependencies]
asap_types.workspace = true
planner-types.workspace = true
asap_sketch_codec = { path = "../asap_sketch_codec" }
asap_sketchlib = { git = "https://github.com/ProjectASAP/asap_sketchlib", branch = "main" }
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
thiserror.workspace = true
async-trait = "0.1"
base64 = "0.21"
bincode = "1.3"
rmp-serde = "1.3"
prost = "0.13"
xxhash-rust = { version = "0.8", features = ["xxh32", "xxh64"] }

[features]
default = []
extra_debugging = []

[dev-dependencies]
tokio.workspace = true
hex = "0.4"
