//! Phase ε.1.5 — Telegraf TOML emitter (per-runtime mirror of
//! [`super::stage_config::emit_edge_yaml`]).
//!
//! `asap-telegraf` is the Telegraf-runtime variant of the ASAP edge
//! agent. Telegraf consumes TOML; the relevant plugins are:
//!
//! * `inputs.opentelemetry` — OTLP gRPC / HTTP receiver (port 4317 /
//!   4318) — provides the upstream OTLP stream.
//! * `processors.allsketches` — the Telegraf-side streaming sketch
//!   processor patched into `telegraf-patch/processors/`. Mirror of the
//!   OTel-collector `*sketchprocessor` family.
//! * `outputs.opentelemetry` — OTLP **gRPC** exporter to the gateway
//!   (Mode 1 / Mode 2). Telegraf's shipped plugin is gRPC-only — see
//!   `telegraf/plugins/outputs/opentelemetry/opentelemetry.go`. There is
//!   no `protocol = "http/protobuf"` field in the upstream plugin.
//! * `outputs.http` — generic HTTP POST output. For Mode 3 we use this
//!   with the `prometheusremotewrite` serializer so the agent can ship
//!   raw samples to Prometheus's remote-write endpoint
//!   (`/api/v1/write`). This is a documented Phase ε.1.5 deviation
//!   from the OTel-collector path's `otlphttp/prometheus` exporter:
//!   Telegraf has no OTLP-HTTP serializer, but Prometheus's
//!   remote-write endpoint accepts the same physical archive that the
//!   OTLP receiver writes to, so the **archive contents end up
//!   identical**. The wire framing differs; the storage outcome does
//!   not.
//!
//! Three modes (mirror the [`crate::planner::wire_cost::BindMode`] enum
//! Phase ε.1 introduced):
//!
//! 1. `SketchAtEdge` — `[[processors.allsketches]]` between
//!    `[[inputs.opentelemetry]]` and `[[outputs.opentelemetry]]`.
//! 2. `RawAtEdgeSketchAtBackend` — passthrough: input → output. No
//!    sketch processor at the edge.
//! 3. `RawAtEdgePrometheusArchive` — passthrough: input →
//!    `[[outputs.http]]` with `data_format = "prometheusremotewrite"`
//!    pointed at Prometheus's `/api/v1/write`.

use anyhow::{Context, Result};

use crate::physical::colored_dag::emitter::{EdgeSketchProcessor, EdgeStageConfig, ExportTarget};
use crate::physical::colored_dag::stage_id::StageId;
use crate::sketch_algebra::params::{SketchKind, SketchParams};

/// Default Prometheus remote-write URL for Mode 3 — Telegraf doesn't
/// support OTLP-HTTP egress, so we land in the same Prometheus archive
/// via remote-write instead. The URL maps to the same Prometheus instance
/// the OTel-collector emitter targets via OTLP HTTP — Prometheus accepts
/// both ingest paths and stores into the same TSDB.
pub const DEFAULT_PROMETHEUS_REMOTE_WRITE_URL: &str = "http://prometheus:9090/api/v1/write";

// ── Public API ───────────────────────────────────────────────────────────────

/// Build the Telegraf TOML for the `asap-telegraf` runtime from a
/// typed L5 [`EdgeStageConfig`].
///
/// `prometheus_remote_write_url` overrides the default Prometheus
/// remote-write endpoint when present (for Mode 3 metrics). `None`
/// falls back to [`DEFAULT_PROMETHEUS_REMOTE_WRITE_URL`].
pub fn emit_telegraf_toml(
    cfg: &EdgeStageConfig,
    prometheus_remote_write_url: Option<&str>,
) -> Result<String> {
    let mut out = String::new();
    out.push_str("# Generated by ASAP controller (Phase ε.1.5).\n");
    out.push_str("# Mode-2/3 detection follows the EdgeStageConfig signals.\n\n");

    // ── inputs.opentelemetry ─────────────────────────────────────────────────
    // Telegraf's OTLP input listens on the default OTLP ports.
    out.push_str("[[inputs.opentelemetry]]\n");
    out.push_str("  service_address = \"0.0.0.0:4317\"\n");
    out.push_str("  http_service_address = \"0.0.0.0:4318\"\n");
    out.push_str("  timeout = \"5s\"\n");
    out.push('\n');

    // ── Mode dispatch ────────────────────────────────────────────────────────
    let has_prometheus_archive = !cfg.prometheus_archive_metrics.is_empty();
    let has_sketch = !cfg.sketch_processors.is_empty();

    if has_prometheus_archive {
        // Mode 3 — Prometheus archive: passthrough, then remote-write
        // to Prometheus. We do NOT include `[[processors.allsketches]]`.
        let url = prometheus_remote_write_url.unwrap_or(DEFAULT_PROMETHEUS_REMOTE_WRITE_URL);
        emit_outputs_http_remote_write(&mut out, url);
    } else if has_sketch {
        // Mode 1 — sketch at edge. One `[[processors.allsketches]]` per
        // sketch processor; outputs.opentelemetry to gateway.
        for sp in &cfg.sketch_processors {
            emit_processors_allsketches(&mut out, sp, cfg.window_secs);
        }
        let endpoint = resolve_export_endpoint("data-plane", &cfg.exporter_target);
        emit_outputs_opentelemetry(&mut out, &endpoint);
    } else {
        // Mode 2 — raw at edge. Passthrough; outputs.opentelemetry
        // ships raw OTLP to the gateway.
        let endpoint = resolve_export_endpoint("data-plane", &cfg.exporter_target);
        emit_outputs_opentelemetry(&mut out, &endpoint);
    }

    // Validate that what we emitted parses as TOML — catches malformed
    // table headers / quoted strings before the agent boots.
    let _: toml_minimal::Document = toml_minimal::Document::parse(&out)
        .with_context(|| format!("generated Telegraf TOML failed minimal parse: {out}"))?;

    Ok(out)
}

// ── Internals ────────────────────────────────────────────────────────────────

fn resolve_export_endpoint(default_host: &str, target: &ExportTarget) -> String {
    match target {
        ExportTarget::Endpoint(s) => s.clone(),
        ExportTarget::Stage(StageId::Edge) => "edge:4317".to_string(),
        ExportTarget::Stage(StageId::Gateway) => format!("{default_host}:4317"),
        ExportTarget::Stage(StageId::Backend) => format!("{default_host}:4317"),
    }
}

fn emit_outputs_opentelemetry(out: &mut String, endpoint: &str) {
    // `outputs.opentelemetry` is gRPC-only; `service_address` takes
    // `host:port` (no scheme). Compression defaults to gzip.
    out.push_str("[[outputs.opentelemetry]]\n");
    out.push_str(&format!("  service_address = \"{endpoint}\"\n"));
    out.push_str("  timeout = \"5s\"\n");
    out.push_str("  compression = \"gzip\"\n");
    out.push('\n');
}

fn emit_outputs_http_remote_write(out: &mut String, url: &str) {
    // Telegraf's `outputs.http` POSTs the serialized batch to the URL.
    // `data_format = "prometheusremotewrite"` selects the remote-write
    // serializer shipped in `telegraf/plugins/serializers/prometheusremotewrite/`.
    out.push_str("[[outputs.http]]\n");
    out.push_str(&format!("  url = \"{url}\"\n"));
    out.push_str("  method = \"POST\"\n");
    out.push_str("  data_format = \"prometheusremotewrite\"\n");
    out.push_str("  content_encoding = \"snappy\"\n");
    out.push_str("  [outputs.http.headers]\n");
    out.push_str("    Content-Type = \"application/x-protobuf\"\n");
    out.push_str("    X-Prometheus-Remote-Write-Version = \"0.1.0\"\n");
    out.push('\n');
}

fn emit_processors_allsketches(
    out: &mut String,
    sp: &EdgeSketchProcessor,
    window_secs: Option<u64>,
) {
    out.push_str("[[processors.allsketches]]\n");
    let mode = if window_secs.is_some() {
        "window"
    } else {
        "batch"
    };
    out.push_str(&format!("  mode = \"{mode}\"\n"));
    if let Some(w) = window_secs {
        out.push_str(&format!("  window_duration = \"{w}s\"\n"));
    }
    // PR 5 alignment (mirroring #244 / #246 / #250's wire cleanups):
    // `aggregation_id` was the controller-allocated string the
    // patched asap-otel processors don't consume — sid identity is
    // content-addressed server-side via `(metric, attrs_fingerprint,
    // agg_kind_canonical)`. Field stays on `EdgeSketchProcessor` as
    // internal emit plumbing; it just doesn't reach the wire here.
    out.push_str(&format!(
        "  sketch_kind = \"{}\"\n",
        sketch_kind_tag(&sp.sketch_kind)
    ));
    match &sp.sketch_params {
        SketchParams::Kll(p) => {
            out.push_str(&format!("  k = {}\n", p.k));
        }
        SketchParams::DDSketch(p) => {
            out.push_str(&format!("  relative_accuracy = {}\n", p.alpha));
            out.push_str("  delta_transmission = true\n");
        }
        SketchParams::Hll(_p) => {
            out.push_str("  delta_transmission = true\n");
        }
        SketchParams::Cms(p) => {
            out.push_str(&format!("  rows = {}\n", p.d));
            out.push_str(&format!("  columns = {}\n", p.w));
            out.push_str("  delta_transmission = true\n");
        }
        SketchParams::CountSketch(p) => {
            let epsilon = std::f64::consts::E / (p.w as f64);
            let delta = 2f64.powi(-(p.d as i32));
            out.push_str(&format!("  epsilon = {epsilon}\n"));
            out.push_str(&format!("  delta = {delta}\n"));
            out.push_str("  delta_transmission = true\n");
        }
    }
    out.push('\n');
}

fn sketch_kind_tag(kind: &SketchKind) -> &'static str {
    match kind {
        SketchKind::Kll => "kll",
        SketchKind::DDSketch => "ddsketch",
        SketchKind::Hll => "hll",
        SketchKind::Cms => "cms",
        SketchKind::CountSketch => "count_sketch",
    }
}

// ── Minimal TOML parser stub ─────────────────────────────────────────────────
//
// The controller crate doesn't depend on a full `toml` crate (the
// existing surface is YAML / JSON only). To validate that our emitted
// TOML is syntactically valid, we ship a tiny purpose-built validator
// that recognizes the subset Telegraf consumes: `[[table.array]]` /
// `[table]` headers, `key = "string"`, `key = number`, `key = bool`,
// indented sub-tables, and `# comments`. This is conservative — it
// rejects malformed table headers / unbalanced quotes / etc., which
// is the failure mode we care about catching before agent boot.

mod toml_minimal {
    use anyhow::{anyhow, Result};

    #[derive(Debug)]
    pub struct Document;

    impl Document {
        pub fn parse(src: &str) -> Result<Self> {
            for (lineno, raw) in src.lines().enumerate() {
                let line = strip_comment(raw).trim();
                if line.is_empty() {
                    continue;
                }
                if line.starts_with('[') {
                    if !is_balanced_brackets(line) {
                        return Err(anyhow!(
                            "line {}: unbalanced [ in table header: {raw}",
                            lineno + 1
                        ));
                    }
                    continue;
                }
                // key = value
                let Some(eq) = line.find('=') else {
                    return Err(anyhow!(
                        "line {}: expected `key = value`, got: {raw}",
                        lineno + 1
                    ));
                };
                let key = line[..eq].trim();
                let val = line[eq + 1..].trim();
                if key.is_empty() {
                    return Err(anyhow!("line {}: empty key in: {raw}", lineno + 1));
                }
                if val.is_empty() {
                    return Err(anyhow!("line {}: empty value in: {raw}", lineno + 1));
                }
                // Validate value: string (balanced quotes), bool, or
                // unquoted scalar (number / fraction).
                if val.starts_with('"') {
                    if !val.ends_with('"') || val.len() < 2 {
                        return Err(anyhow!("line {}: unbalanced \" in: {raw}", lineno + 1));
                    }
                }
            }
            Ok(Document)
        }
    }

    fn strip_comment(line: &str) -> &str {
        // Strip a trailing `# ...` comment, but not when inside quotes.
        let mut in_str = false;
        for (i, c) in line.char_indices() {
            match c {
                '"' => in_str = !in_str,
                '#' if !in_str => return &line[..i],
                _ => {}
            }
        }
        line
    }

    fn is_balanced_brackets(s: &str) -> bool {
        let mut depth = 0i32;
        for c in s.chars() {
            match c {
                '[' => depth += 1,
                ']' => depth -= 1,
                _ => {}
            }
            if depth < 0 {
                return false;
            }
        }
        depth == 0
    }
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::physical::colored_dag::emitter::{EdgeSketchProcessor, PrometheusArchiveMetric};
    use crate::sketch_algebra::params::{DDSketchParams, KllParams};

    fn ddsketch_edge_cfg_mode1() -> EdgeStageConfig {
        EdgeStageConfig {
            source_metric: Some("http_request_duration_seconds".to_string()),
            label_filters: Vec::new(),
            window_secs: Some(60),
            sketch_processors: vec![EdgeSketchProcessor {
                processor_name: "ddsketch".to_string(),
                sketch_kind: SketchKind::DDSketch,
                sketch_params: SketchParams::DDSketch(DDSketchParams { alpha: 0.01 }),
                aggregation_id: "agg0".to_string(),
            }],
            exporter_target: ExportTarget::Stage(StageId::Gateway),
            prometheus_archive_metrics: Vec::new(),
            archive_tier_metrics: Vec::new(),
            warm_passthrough_metrics: Vec::new(),
            metric_to_family: std::collections::HashMap::new(),
            metric_to_grouping_labels: std::collections::HashMap::new(),
            cumulative_counter_metrics: Vec::new(),
            cold_ship_endpoint: None,
            cold_external_labels: Vec::new(),
            metric_to_sample_p: std::collections::HashMap::new(),
            metric_to_distinct_keys: std::collections::HashMap::new(),
            metric_to_item_label: std::collections::HashMap::new(),
            cold_format: crate::physical::colored_dag::emitter::ColdFormat::default(),
            cold_coldpart_endpoint: None,
        }
    }

    fn raw_edge_cfg_mode2() -> EdgeStageConfig {
        EdgeStageConfig {
            source_metric: Some("http_request_duration_seconds".to_string()),
            label_filters: Vec::new(),
            window_secs: Some(60),
            sketch_processors: Vec::new(),
            exporter_target: ExportTarget::Stage(StageId::Gateway),
            prometheus_archive_metrics: Vec::new(),
            archive_tier_metrics: Vec::new(),
            warm_passthrough_metrics: Vec::new(),
            metric_to_family: std::collections::HashMap::new(),
            metric_to_grouping_labels: std::collections::HashMap::new(),
            cumulative_counter_metrics: Vec::new(),
            cold_ship_endpoint: None,
            cold_external_labels: Vec::new(),
            metric_to_sample_p: std::collections::HashMap::new(),
            metric_to_distinct_keys: std::collections::HashMap::new(),
            metric_to_item_label: std::collections::HashMap::new(),
            cold_format: crate::physical::colored_dag::emitter::ColdFormat::default(),
            cold_coldpart_endpoint: None,
        }
    }

    fn prom_edge_cfg_mode3() -> EdgeStageConfig {
        EdgeStageConfig {
            source_metric: Some("http_request_duration_seconds".to_string()),
            label_filters: Vec::new(),
            window_secs: Some(60),
            sketch_processors: Vec::new(),
            exporter_target: ExportTarget::Stage(StageId::Gateway),
            prometheus_archive_metrics: vec![PrometheusArchiveMetric {
                metric: "http_request_duration_seconds".to_string(),
                window_secs: Some(60),
                label_proj: vec!["service.name".to_string()],
            }],
            archive_tier_metrics: Vec::new(),
            warm_passthrough_metrics: Vec::new(),
            metric_to_family: std::collections::HashMap::new(),
            metric_to_grouping_labels: std::collections::HashMap::new(),
            cumulative_counter_metrics: Vec::new(),
            cold_ship_endpoint: None,
            cold_external_labels: Vec::new(),
            metric_to_sample_p: std::collections::HashMap::new(),
            metric_to_distinct_keys: std::collections::HashMap::new(),
            metric_to_item_label: std::collections::HashMap::new(),
            cold_format: crate::physical::colored_dag::emitter::ColdFormat::default(),
            cold_coldpart_endpoint: None,
        }
    }

    /// Mode 1 snapshot — sketch at edge.
    /// `[[inputs.opentelemetry]]` + `[[processors.allsketches]]` +
    /// `[[outputs.opentelemetry]]`.
    #[test]
    fn telegraf_toml_mode1_sketch_at_edge_shape() {
        let toml =
            emit_telegraf_toml(&ddsketch_edge_cfg_mode1(), None).expect("emit_telegraf_toml ok");
        assert!(
            toml.contains("[[inputs.opentelemetry]]"),
            "missing input\n{toml}"
        );
        assert!(
            toml.contains("[[processors.allsketches]]"),
            "missing sketch processor\n{toml}"
        );
        assert!(
            toml.contains("[[outputs.opentelemetry]]"),
            "missing output\n{toml}"
        );
        assert!(
            toml.contains("service_address = \"data-plane:4317\""),
            "missing data-plane endpoint\n{toml}"
        );
        // Sketch params preserved.
        assert!(
            toml.contains("relative_accuracy = 0.01"),
            "missing alpha\n{toml}"
        );
        assert!(
            toml.contains("sketch_kind = \"ddsketch\""),
            "wrong kind\n{toml}"
        );
    }

    /// Mode 2 snapshot — raw at edge. No `[[processors.allsketches]]`.
    /// `[[outputs.opentelemetry]]` ships raw OTLP to the gateway.
    #[test]
    fn telegraf_toml_mode2_raw_at_edge_shape() {
        let toml = emit_telegraf_toml(&raw_edge_cfg_mode2(), None).expect("emit_telegraf_toml ok");
        assert!(
            toml.contains("[[inputs.opentelemetry]]"),
            "missing input\n{toml}"
        );
        assert!(
            !toml.contains("[[processors.allsketches]]"),
            "Mode 2 must not include sketch processor\n{toml}"
        );
        assert!(
            toml.contains("[[outputs.opentelemetry]]"),
            "missing output\n{toml}"
        );
        assert!(
            toml.contains("service_address = \"data-plane:4317\""),
            "missing data-plane endpoint\n{toml}"
        );
    }

    /// Mode 3 snapshot — Prometheus archive. `[[outputs.http]]` POSTs
    /// to Prometheus's remote-write endpoint `/api/v1/write` (Telegraf
    /// has no OTLP-HTTP serializer; remote-write lands in the same
    /// Prometheus TSDB the OTel-collector path lands in via OTLP HTTP).
    #[test]
    fn telegraf_toml_mode3_prometheus_archive_shape() {
        let toml = emit_telegraf_toml(&prom_edge_cfg_mode3(), None).expect("emit_telegraf_toml ok");
        assert!(
            toml.contains("[[inputs.opentelemetry]]"),
            "missing input\n{toml}"
        );
        assert!(
            !toml.contains("[[processors.allsketches]]"),
            "Mode 3 must not include sketch processor\n{toml}"
        );
        assert!(
            toml.contains("[[outputs.http]]"),
            "missing http output\n{toml}"
        );
        assert!(
            toml.contains("url = \"http://prometheus:9090/api/v1/write\""),
            "missing Prometheus remote-write URL\n{toml}"
        );
        assert!(
            toml.contains("data_format = \"prometheusremotewrite\""),
            "missing remote-write serializer\n{toml}"
        );
        // No outputs.opentelemetry — Mode 3 is a passthrough to
        // Prometheus, not the gateway.
        assert!(
            !toml.contains("[[outputs.opentelemetry]]"),
            "Mode 3 must not also export to gateway\n{toml}"
        );
    }

    /// Mode 3 with override URL — caller can redirect to a different
    /// Prometheus instance.
    #[test]
    fn telegraf_toml_mode3_url_override() {
        let toml = emit_telegraf_toml(
            &prom_edge_cfg_mode3(),
            Some("https://prom-prod:9090/api/v1/write"),
        )
        .expect("emit_telegraf_toml ok");
        assert!(
            toml.contains("https://prom-prod:9090/api/v1/write"),
            "override URL not propagated\n{toml}"
        );
    }

    /// Catch malformed output early — emit_telegraf_toml should produce
    /// TOML that round-trips through our minimal validator.
    #[test]
    fn telegraf_toml_all_modes_parse() {
        for (name, cfg) in [
            ("mode1", ddsketch_edge_cfg_mode1()),
            ("mode2", raw_edge_cfg_mode2()),
            ("mode3", prom_edge_cfg_mode3()),
        ] {
            let toml = emit_telegraf_toml(&cfg, None)
                .unwrap_or_else(|e| panic!("emit failed for {name}: {e}"));
            // Parsing happens inside emit_telegraf_toml; if we got Ok,
            // parsing succeeded. Spot-check a handful of expected
            // tokens defensively.
            assert!(
                toml.contains("inputs.opentelemetry"),
                "{name}: missing input header"
            );
        }
    }

    /// KLL params — k is preserved, no delta_transmission flag (KLL has
    /// no delta variant per Implementation.tex).
    #[test]
    fn telegraf_toml_mode1_kll_no_delta_flag() {
        let cfg = EdgeStageConfig {
            source_metric: Some("metric".to_string()),
            label_filters: Vec::new(),
            window_secs: Some(60),
            sketch_processors: vec![EdgeSketchProcessor {
                processor_name: "KLL".to_string(),
                sketch_kind: SketchKind::Kll,
                sketch_params: SketchParams::Kll(KllParams { k: 200 }),
                aggregation_id: "agg0".to_string(),
            }],
            exporter_target: ExportTarget::Stage(StageId::Gateway),
            prometheus_archive_metrics: Vec::new(),
            archive_tier_metrics: Vec::new(),
            warm_passthrough_metrics: Vec::new(),
            metric_to_family: std::collections::HashMap::new(),
            metric_to_grouping_labels: std::collections::HashMap::new(),
            cumulative_counter_metrics: Vec::new(),
            cold_ship_endpoint: None,
            cold_external_labels: Vec::new(),
            metric_to_sample_p: std::collections::HashMap::new(),
            metric_to_distinct_keys: std::collections::HashMap::new(),
            metric_to_item_label: std::collections::HashMap::new(),
            cold_format: crate::physical::colored_dag::emitter::ColdFormat::default(),
            cold_coldpart_endpoint: None,
        };
        let toml = emit_telegraf_toml(&cfg, None).expect("emit ok");
        assert!(toml.contains("k = 200"), "k not propagated\n{toml}");
        assert!(toml.contains("sketch_kind = \"kll\""), "kind\n{toml}");
        // KLL has no delta variant — flag must be absent.
        assert!(
            !toml.contains("delta_transmission"),
            "KLL must not have delta_transmission\n{toml}"
        );
    }
}
